import React from 'react';
import { Activity, AlertTriangle, ArrowDownCircle, ArrowUpCircle, Bot, ChevronRight, CircleDollarSign, Clock3, Crown, DollarSign, Eye, Home, Landmark, ReceiptText, ShieldCheck, Trophy, Users, WalletCards, Wifi } from 'lucide-react';
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts';
import { formatCurrency } from '../../utils/number';
import MonthlyStatsChart from './MonthlyStatsChart';

const REVENUE_META = [
  ['game_rake', 'Solo rake', '#f59e0b'], ['team_game_rake', 'Team rake', '#3b82f6'], ['forfeit_rake', 'Forfeit rake', '#f97316'],
  ['betting_margin', 'Live-bet commission', '#10b981'], ['bot_result', 'Bot economy', '#8b5cf6'], ['vip_subscription', 'VIP sales', '#ec4899'],
  ['tournament_margin', 'Tournament margin', '#06b6d4'], ['tournament_cancellation_fee', 'Tournament cancellation', '#64748b'], ['withdrawal_fee', 'Withdrawal fees', '#ef4444'],
] as const;
const RATE_META = [
  ['gameRakeRate', 'Game rake', 'rate'], ['spectatorBetCommissionRate', 'Live bet', 'rate'], ['botWinCharge', 'Bot loss charge', 'amount'],
  ['botPlayerWinReward', 'Bot win reward', 'amount'], ['tournamentCommissionRate', 'Tournament margin', 'rate'], ['noPlayWithdrawalFeeRate', 'No-play withdrawal', 'rate'],
  ['normalWithdrawalFeeRate', 'Standard withdrawal', 'rate'], ['manualForfeitPenaltyRate', 'Manual exit', 'rate'], ['inactivityPenaltyRate', 'Inactivity', 'rate'],
  ['depositFeeRate', 'Deposit fee', 'rate'], ['privateMatchFeeRate', 'Private match', 'rate'],
] as const;

const MetricCard = ({ label, value, note, icon: Icon, tone = 'indigo' }) => {
  const tones = { indigo: 'from-indigo-600 to-violet-700', emerald: 'from-emerald-500 to-teal-700', rose: 'from-rose-500 to-red-700', sky: 'from-sky-500 to-blue-700' };
  return <div className={`relative overflow-hidden rounded-2xl bg-gradient-to-br ${tones[tone]} p-5 text-white shadow-[0_14px_35px_rgba(15,23,42,.13)]`}><div className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/10"/><div className="relative flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-white/65">{label}</p><p className="mt-2 text-3xl font-black tracking-tight">{value}</p><p className="mt-2 text-xs text-white/70">{note}</p></div><span className="rounded-2xl border border-white/15 bg-white/10 p-3"><Icon size={23}/></span></div></div>;
};
const ActionRow = ({ icon: Icon, label, value, note, color = 'text-indigo-600', onClick = undefined }) => <button type="button" onClick={onClick} className="group flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left transition hover:bg-slate-50"><span className={`rounded-xl bg-slate-50 p-2.5 ${color}`}><Icon size={18}/></span><span className="min-w-0 flex-1"><span className="block text-xs font-bold text-slate-500">{label}</span><span className="block truncate text-[11px] text-slate-400">{note}</span></span><strong className="text-sm text-slate-900">{value}</strong>{onClick && <ChevronRight size={16} className="text-slate-300 group-hover:text-indigo-500"/>}</button>;
const RoomAvatar = ({ player }) => {
  const avatar = String(player.avatar || '').trim();
  const isImage = /^(https?:\/\/|data:image\/|blob:|\/api\/profile-images\/|\/uploads\/)/i.test(avatar);
  return <span title={player.username} className="flex h-9 w-9 shrink-0 items-center justify-center overflow-hidden rounded-full border-2 border-white bg-slate-100 text-lg shadow-sm">{isImage ? <img src={avatar} alt={player.username || 'Player'} className="h-full w-full object-cover" referrerPolicy="no-referrer"/> : (avatar || '🎮')}</span>;
};
const RoomCard = ({ room }) => <div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center justify-between"><span className="rounded-lg bg-slate-100 px-2 py-1 font-mono text-[10px] font-bold text-slate-500">#{room.id}</span><strong className="text-sm text-emerald-600">{formatCurrency(room.betAmount)}</strong></div><div className="mt-4 flex items-center justify-between"><div className="flex -space-x-2">{room.players.map(player => <RoomAvatar key={player.userId} player={player}/>)}</div><button onClick={() => window.open(`/${room.id}?spectate=true`, '_blank')} className="flex items-center gap-1 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Eye size={14}/> Watch</button></div></div>;

const StatsGrid = ({ stats, rooms = [], manualTransactions = [], setView }) => {
  if (!stats) return <div className="rounded-2xl bg-white p-12 text-center text-slate-500 shadow-sm">Loading platform intelligence...</div>;
  const revenue = stats.revenueBreakdown || {};
  const revenueChart = REVENUE_META.map(([key, name, color]) => ({ key, name, color, value: Number(revenue[key] || 0) })).filter(item => item.value > 0);
  const activeRooms = rooms.filter(room => room.status === 'playing');
  const pendingDeposits = manualTransactions.filter(tx => tx.managedBy !== 'agent' && tx.transactionType === 'deposit' && tx.status === 'pending').length;
  const pendingWithdrawals = manualTransactions.filter(tx => tx.managedBy !== 'agent' && tx.transactionType === 'withdraw' && tx.status === 'pending').length;
  const totalCosts = Number(stats.welcomeBonusCost || 0) + Number(stats.agentCommissionDiscounts || 0) + Number(stats.cashierPayrollPaid || 0);
  const revenueIcons = [Trophy, Users, Activity, CircleDollarSign, Bot, Crown, Trophy, ReceiptText, ArrowDownCircle];

  return <div className="min-w-0 space-y-5 pb-8">
    <section className="relative overflow-hidden rounded-[28px] bg-[#08111f] p-5 text-white shadow-2xl sm:p-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_85%_15%,rgba(16,185,129,.25),transparent_35%),radial-gradient(circle_at_20%_80%,rgba(79,70,229,.3),transparent_38%)]"/><div className="relative flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.25em] text-emerald-300"><ShieldCheck size={15}/> Super Admin Intelligence</div><h2 className="mt-3 text-2xl font-black tracking-tight sm:text-4xl">Platform command center</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-400">Revenue, operations, customer activity and financial risk—organized into one clear live view.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><MiniDark label="Live users" value={stats.onlineClients || 0} icon={Wifi}/><MiniDark label="Playing" value={stats.activeRooms || 0}/><MiniDark label="Waiting" value={stats.waitingRooms || 0}/></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Net earnings" value={formatCurrency(stats.netPlatformEarnings || 0)} note={`Revenue less ${formatCurrency(totalCosts)} costs`} icon={Landmark} tone="emerald"/><MetricCard label="Gross revenue" value={formatCurrency(stats.houseRevenue || 0)} note="All recorded platform income" icon={CircleDollarSign}/><MetricCard label="Registered users" value={stats.totalUsers || 0} note={`${stats.onlineClients || 0} connected right now`} icon={Users} tone="sky"/><MetricCard label="Pending review" value={stats.pendingAdminTransactions || 0} note={`${stats.totalTransactions || 0} wallet records`} icon={AlertTriangle} tone="rose"/></section>
    <section className="grid min-w-0 gap-5 xl:grid-cols-5"><div className="min-w-0 rounded-2xl border border-slate-200 bg-white p-1 shadow-sm xl:col-span-3"><MonthlyStatsChart data={stats.monthlyActivity}/></div><div className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6 xl:col-span-2"><p className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">Revenue mix</p><h3 className="mt-1 text-xl font-black text-slate-900">Where income comes from</h3>{revenueChart.length ? <><div className="h-52"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={revenueChart} dataKey="value" nameKey="name" innerRadius={54} outerRadius={82} paddingAngle={3}>{revenueChart.map(item => <Cell key={item.key} fill={item.color}/>)}</Pie><Tooltip formatter={(value: number) => formatCurrency(value)}/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2">{revenueChart.map(item => <div key={item.key} className="flex min-w-0 items-center gap-2 text-xs"><i className="h-2.5 w-2.5 shrink-0 rounded-full" style={{background:item.color}}/><span className="min-w-0 flex-1 truncate text-slate-500">{item.name}</span><strong>{formatCurrency(item.value)}</strong></div>)}</div></> : <div className="flex h-64 items-center justify-center text-sm text-slate-400">Revenue appears here after settlements.</div>}</div></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><SectionTitle kicker="Income ledger" title="Revenue sources" value={formatCurrency(stats.houseRevenue || 0)}/><div className="grid gap-1 sm:grid-cols-2">{REVENUE_META.map(([key,label], index) => <ActionRow key={key} icon={revenueIcons[index]} label={label} value={formatCurrency(revenue[key] || 0)} note={Number(revenue[key] || 0) > 0 ? 'Recorded earnings' : 'No earnings recorded yet'} color={Number(revenue[key] || 0) > 0 ? 'text-emerald-600' : 'text-slate-400'}/>)}</div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><SectionTitle kicker="Costs & obligations" title="Not revenue"/><ActionRow icon={DollarSign} label="Welcome bonuses" value={formatCurrency(stats.welcomeBonusCost || 0)} note="Promotional cost" color="text-rose-500"/><ActionRow icon={ArrowDownCircle} label="Agent commissions" value={formatCurrency(stats.agentCommissionDiscounts || 0)} note="Distribution cost" color="text-orange-500"/><ActionRow icon={WalletCards} label="Cashier payroll" value={formatCurrency(stats.cashierPayrollPaid || 0)} note="Salary and bonuses" color="text-violet-500"/><ActionRow icon={CircleDollarSign} label="Agent float issued" value={formatCurrency(stats.agentFloatIssued || 0)} note="Liability, not income" color="text-slate-500"/></div></section>
    {stats.revenueControl && <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><SectionTitle kicker="Configured economics" title="Active rates & future controls"/><p className="mb-4 text-xs text-slate-500">A zero value is inactive. Change these only from Settings → Revenue Control.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{RATE_META.map(([key,label,kind]) => { const value=Number(stats.revenueControl[key]||0); return <div key={key} className={`rounded-xl border p-3 ${value>0?'border-emerald-200 bg-emerald-50/60':'border-slate-200 bg-slate-50'}`}><div className="flex items-center justify-between gap-2"><span className="text-xs font-bold text-slate-600">{label}</span><i className={`h-2 w-2 rounded-full ${value>0?'bg-emerald-500':'bg-slate-300'}`}/></div><strong className={`mt-2 block text-xl ${value>0?'text-emerald-700':'text-slate-400'}`}>{kind==='rate'?`${(value*100).toFixed(2)}%`:formatCurrency(value)}</strong></div>})}</div></section>}
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><h3 className="mb-3 flex items-center gap-2 text-lg font-black text-slate-900"><AlertTriangle className="text-amber-500" size={20}/> Action queue</h3><div className="grid gap-1 sm:grid-cols-3"><ActionRow icon={ArrowUpCircle} label="Pending deposits" value={pendingDeposits} note="Requires decision" color="text-emerald-600" onClick={()=>setView('manual-transactions')}/><ActionRow icon={ArrowDownCircle} label="Pending withdrawals" value={pendingWithdrawals} note="Requires decision" color="text-red-600" onClick={()=>setView('manual-transactions')}/><ActionRow icon={CircleDollarSign} label="Agent requests" value={stats.pendingAgentRequests||0} note="Float approvals" color="text-violet-600" onClick={()=>setView('agent-requests')}/></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h3 className="mb-3 text-lg font-black text-slate-900">Operations</h3><ActionRow icon={Home} label="Rooms" value={stats.totalRooms||0} note={`${stats.completedRooms||0} completed`} onClick={()=>setView('rooms')}/><ActionRow icon={ShieldCheck} label="Agents" value={`${stats.activeAgents||0}/${stats.totalAgents||0}`} note="Active / total" onClick={()=>setView('agents')}/><ActionRow icon={Trophy} label="Tournaments" value={stats.openTournaments||0} note={`${stats.activeTournaments||0} running`} onClick={()=>setView('tournaments')}/></div></section>
    <section className="grid gap-5 xl:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm xl:col-span-2"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-black text-slate-900">Live games</h3><span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">{activeRooms.length} active</span></div>{activeRooms.length?<div className="grid gap-3 sm:grid-cols-2">{activeRooms.slice(0,6).map(room=><RoomCard key={room.id} room={room}/>)}</div>:<div className="py-12 text-center text-sm text-slate-400"><Activity className="mx-auto mb-2"/>No live games right now.</div>}</div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="text-lg font-black text-slate-900">Recent activity</h3><Clock3 size={18} className="text-slate-400"/></div>{(stats.recentActivity||[]).slice(0,6).map(item=><div key={`${item.kind}-${item.id}`} className="rounded-xl px-3 py-3 hover:bg-slate-50"><div className="flex justify-between gap-3"><p className="line-clamp-2 text-xs font-bold text-slate-700">{item.title}</p>{item.amount!==undefined&&<strong className="whitespace-nowrap text-xs">{formatCurrency(item.amount)}</strong>}</div><p className="mt-1 text-[10px] text-slate-400">{new Date(item.timestamp).toLocaleString()}</p></div>)}</div></section>
  </div>;
};

const MiniDark = ({label,value,icon:Icon = null}) => <div className="rounded-2xl border border-white/10 bg-white/5 px-4 py-3"><span className="text-[10px] uppercase text-slate-500">{label}</span><strong className="mt-1 flex items-center gap-2 text-xl">{Icon&&<Icon size={16} className="text-emerald-400"/>}{value}</strong></div>;
const SectionTitle = ({kicker,title,value = undefined}) => <div className="mb-4 flex items-end justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[.18em] text-indigo-600">{kicker}</p><h3 className="text-xl font-black text-slate-900">{title}</h3></div>{value&&<strong className="text-xl text-emerald-600">{value}</strong>}</div>;
export default StatsGrid;
