import { ArrowLeft, Eye, Gamepad2, HeartHandshake, Radio, ShieldCheck, Sparkles, Target, Trophy, Users, Wallet } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { useBodyScrollLock } from '../hooks/useBodyScrollLock';

interface AboutUsProps { onClose: () => void; }

export default function AboutUs({ onClose }: AboutUsProps) {
  useBodyScrollLock();
  const { language } = useLanguage();
  const so = language === 'so';
  const features = [
    [Gamepad2, so ? 'Ciyaaro kala duwan' : 'Multiple game modes', so ? 'Solo 1v1 ama afar qof, Partnership 2v2, Qol Gaar ah, Raadin Toos ah iyo Bot.' : 'Solo 1v1 or four-player, Partnership 2v2, Private Rooms, Live Search and Bot play.'],
    [Radio, so ? 'Waqti-dhab ah' : 'Real-time play', so ? 'Laadhuuga, dhaqaaqa xoolaha, waqtiga wareegga iyo natiijada waxaa wada arka ciyaartoyda iyo daawadayaasha.' : 'Players and spectators see dice rolls, token moves, turn timers and results in real time.'],
    [Wallet, so ? 'Boorsada isku xiran' : 'Integrated wallet', so ? 'Dhigaal, la-bixid, saamiga ciyaarta, lacag-bixinta iyo xaaladda macaamilka waxay ku wada jiraan koontadaada.' : 'Deposits, withdrawals, game stakes, payouts and transaction status are managed from your account.'],
    [Eye, so ? 'Daawasho iyo saadaal' : 'Spectating and betting', so ? 'Ciyaaraha socda waa la daawan karaa; qofka galay koontadiisana wuxuu ka dooran karaa GUUL ama GUULDARRO suuqa furan.' : 'Watch live games and, when signed in, choose WIN or LOSS while the betting market is open.'],
    [Trophy, so ? 'Tartamo iyo horumar' : 'Competition and progress', so ? 'Kala-sarraynta, tartamada, tirakoobka guulaha iyo guuldarrooyinka iyo VIP-ku waxay ku siinayaan yool joogto ah.' : 'Leaderboards, tournaments, win/loss statistics and VIP plans give every player a goal to pursue.'],
    [ShieldCheck, so ? 'Server-ku xaqiijiyo' : 'Server-authoritative', so ? 'Server-ka ayaa xaqiijiya wareegga, natiijada laadhuuga, dhaqaaqa saxda ah, guusha iyo xisaabinta lacagta.' : 'The server validates turns, dice results, legal moves, winners and financial settlement.'],
  ];
  const flow = so
    ? [['1','Dooro habka','Dooro saamiga, 2 ama 4 ciyaaryahan, kadib Keli ama Koox.'],['2','Hel ciyaar','Raadin Toos ah, Challenge, Qol Gaar ah ama Bot ka dooro.'],['3','Ciyaar wareeggaaga','Tuur laadhuuga, dooro dhaqaaq sax ah, kana war hay waqtiga.'],['4','Hel natiijada','Server-ku wuxuu xaqiijiyaa guusha, lacag-bixinta, tirakoobka iyo xisaabinta saadaasha.']]
    : [['1','Choose a mode','Select a stake, 2 or 4 players, then Solo or Team.'],['2','Find a match','Choose Live Search, Challenge, Private Room or Bot.'],['3','Play your turn','Roll the dice, choose a legal move and watch the timer.'],['4','Receive the result','The server confirms the winner, payout, statistics and bet settlement.']];
  return <div className="fixed inset-0 z-[150] overflow-y-auto overscroll-contain touch-pan-y bg-[#050313] text-white [-webkit-overflow-scrolling:touch]">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_12%_8%,rgba(124,58,237,.28),transparent_32%),radial-gradient(circle_at_88%_30%,rgba(14,165,233,.14),transparent_28%)]" />
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#08051a]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 sm:px-7"><button onClick={onClose} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-black"><ArrowLeft className="h-4 w-4" /> {so ? 'Bogga Hore' : 'Home'}</button><div className="flex items-center gap-2"><img src="/ludosom-logo.png" alt="LudoSom" className="h-9 w-9 rounded-xl object-cover" /><div><div className="text-xs font-black">{so ? 'Nagu Saabsan' : 'About LudoSom'}</div><div className="text-[8px] font-bold uppercase tracking-widest text-purple-300">{so ? 'Cidda aan nahay' : 'Who we are'}</div></div></div></div></header>
    <main className="relative mx-auto max-w-5xl px-4 pb-20 pt-9 sm:px-7 sm:pt-14">
      <section className="rounded-[28px] border border-purple-400/20 bg-gradient-to-br from-purple-950/80 via-slate-950/90 to-blue-950/70 p-6 shadow-2xl sm:p-10"><span className="inline-flex items-center gap-2 rounded-full border border-amber-300/20 bg-amber-300/10 px-3 py-1.5 text-[9px] font-black uppercase tracking-widest text-amber-200"><Sparkles className="h-3 w-3" /> {so ? "Faa'iido Qarsoon" : 'Hidden Advantage'}</span><h1 className="mt-5 max-w-3xl text-3xl font-black leading-tight sm:text-5xl">{so ? 'Ludo Soomaaliyeed oo isku keenta ciyaar, tartan iyo bulsho.' : 'A Somali Ludo experience that brings together play, competition and community.'}</h1><p className="mt-5 max-w-3xl text-sm font-medium leading-7 text-slate-300">{so ? 'LudoSom waa madal Ludo online ah oo kuu sahlaysa inaad hesho qof aad la tartanto, asxaabta qol gaar ah kula ciyaarto, Bot ku tababarto, ciyaaraha socda daawato ama tartan uga qayb gasho—web iyo Android app labadaba.' : 'LudoSom is an online Ludo platform where you can find opponents, play with friends in private rooms, practise against a Bot, watch live games or enter tournaments—on both web and Android.'}</p></section>
      <section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{features.map(([Icon, title, text]: any) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[.045] p-5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-500/15 text-purple-300"><Icon className="h-5 w-5" /></span><h2 className="mt-4 text-sm font-black">{title}</h2><p className="mt-2 text-[11px] font-medium leading-5 text-slate-400">{text}</p></article>)}</section>
      <section className="mt-6 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><div className="flex items-center gap-3"><Target className="h-6 w-6 text-amber-300" /><h2 className="text-xl font-black">{so ? 'Ujeeddadeenna' : 'Our mission'}</h2></div><p className="mt-4 text-sm leading-7 text-slate-300">{so ? 'Waxaan dhiseynaa ciyaar uu qof cusub si fudud u fahmi karo, ciyaaryahan khibrad lehna ka heli karo tartan dhab ah. Martidu app-ka way baran kartaa oo ciyaar socota way daawan kartaa; gelitaanka koontada waxaa loo baahan yahay marka la ciyaarayo, lacag la isticmaalayo ama bulshada lala falgalayo.' : 'We are building a game that is easy for newcomers to understand and competitive enough for experienced players. Guests can explore the app and watch live games; signing in is required to play, use money or interact with the community.'}</p></article><article className="rounded-3xl border border-white/10 bg-slate-950/70 p-6"><div className="flex items-center gap-3"><HeartHandshake className="h-6 w-6 text-emerald-300" /><h2 className="text-xl font-black">{so ? 'Bulsho iyo ixtiraam' : 'Community and respect'}</h2></div><p className="mt-4 text-sm leading-7 text-slate-300">{so ? 'Ciyaartoyda Online-ka ah iyo Challenge-ku waxay isku xiraan dadka bogga Hore jooga. Wada-hadalka, falcelinta iyo daawadayaashu waxay abuuraan jawi bulsho. Ciyaar wanaag iyo xushmaynta dadka kale waa qayb muhiim ah oo LudoSom ah.' : 'Online Players and Challenges connect people waiting on Home. Chat, reactions and spectators create a social atmosphere. Fair play, good conduct and respect for other players are essential to LudoSom.'}</p></article></section>
      <section className="mt-6 rounded-3xl border border-blue-400/15 bg-blue-500/[.06] p-6 sm:p-8"><h2 className="text-xl font-black">{so ? 'Sida LudoSom u shaqeeyo' : 'How LudoSom works'}</h2><div className="mt-6 grid gap-4 sm:grid-cols-2">{flow.map(([n,t,x])=><div key={n} className="flex gap-3"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-blue-500 text-xs font-black">{n}</span><div><h3 className="text-sm font-black">{t}</h3><p className="mt-1 text-[11px] leading-5 text-slate-400">{x}</p></div></div>)}</div></section>
      <section className="mt-6 rounded-3xl border border-amber-300/15 bg-amber-300/[.05] p-6"><h2 className="text-lg font-black">{so ? "Mas'uuliyad iyo hufnaan" : 'Responsibility and transparency'}</h2><p className="mt-3 text-xs leading-6 text-slate-300">{so ? 'Saami ama saadaal ku dhig keliya lacag aad awooddo. Hubi qadarka ka hor gudbinta. Ha siin qof kale erayga sirta ah, OTP ama xogta boorsada. Natiijada iyo lacag-bixintu waxay ku xiran yihiin xaaladda server-ku xaqiijiyey.' : 'Only stake or bet money you can afford. Check the amount before submitting. Never share your password, OTP or wallet details. Results and payouts are based on the state verified by the server.'}</p></section>
      <footer className="mt-10 text-center"><div className="flex items-center justify-center gap-2 text-sm font-black"><Users className="h-4 w-4 text-purple-300" /> {so ? 'Ku soo dhowow LudoSom' : 'Welcome to LudoSom'}</div><p className="mt-2 text-[10px] text-slate-500">{so ? 'Si caddaalad ah u ciyaar · Ciyaartoyda ixtiraam · Ciyaarta ku raaxayso' : 'Play fair · Respect players · Enjoy the game'}</p></footer>
    </main>
  </div>;
}
