import { ArrowLeft, CircleDollarSign, Eye, Gamepad2, HelpCircle, Radio, Search, ShieldAlert, Smartphone, UserPlus, Users, Wallet, Wifi } from 'lucide-react';
import { useLanguage } from '../context/LanguageContext';
import { useBodyScrollLock } from '../hooks/useBodyScrollLock';

interface HelpProps { onClose: () => void; }

const guides = {
  en: [
    [UserPlus, '1. Create an account or sign in', ['Explore Home freely as a guest.', 'Tap Login, Wallet, Search, Bot or another protected action.', 'Choose Sign In or Sign Up in the sheet.', 'Enter your email or phone and password, or use Google.', 'If requested, enter the six-digit OTP sent to you.']],
    [Search, '2. Live Search and Radar', ['Select an amount under Choose Bet Stake.', 'Choose 2 or 4 players.', 'For four players, choose Solo or Partnership 2v2.', 'Tap Search Live Players.', 'Radar displays joined players and starts when every seat is filled.']],
    [Users, '3. Challenge and Private Room', ['Tap Online to see players waiting on Home.', 'Tap Challenge beside your chosen player.', 'They have a limited time to accept or decline.', 'Create a lobby and send its room code to friends.', 'To join, enter the room code and tap the entry arrow.']],
    [Gamepad2, '4. How to play', ['Tap the dice when it is your turn.', 'A six can release a token from its base.', 'Choose an available token; illegal moves are rejected by the server.', 'A sole movable token may move automatically.', 'Bring every token home first to win; partners cooperate in Team mode.']],
    [Eye, '5. Spectating and betting', ['Choose Watch from Live Games.', 'Guests can watch without signing in.', 'Dice, turns and token movement appear in real time.', 'Betting requires an account and sufficient wallet balance.', 'Choose a player or team, WIN or LOSS, a stake, then Submit.']],
    [Wallet, '6. Wallet and money', ['Tap Wallet in the header.', 'For deposits, choose a provider and amount, then follow the instructions.', 'For withdrawals, enter the amount and receiving number.', 'A request can be Pending, Approved or Rejected.', 'Always check your balance, fee and transaction status.']],
  ],
  so: [
    [UserPlus, '1. Koonto samee ama gal', ['Marti ahaan Bogga Hore oo dhan waad arki kartaa.', 'Taabo Gelid, Boorsada, Raadin, Bot ama fal koonto u baahan.', 'Sheet-ka ka dooro Gal ama Is-diiwaangeli.', 'Geli iimaylka ama telefoonka iyo erayga sirta ah, ama Google isticmaal.', 'Haddii OTP lagu weydiiyo, geli lixda lambar ee laguu soo diray.']],
    [Search, '2. Raadin Toos ah iyo Raadaarka', ['Dooro lacagta ciyaarta qaybta Doorashada Saamiga.', 'Dooro 2 ama 4 ciyaaryahan.', 'Haddii ay afar yihiin, dooro Keli ama Iskaashi 2v2.', 'Taabo Raadi Ciyaartoy Toos ah.', 'Raadaarku wuxuu muujinayaa dadka soo biiray; ciyaartu way bilaabataa marka boosasku buuxsamaan.']],
    [Users, '3. Challenge iyo Qol Gaar ah', ['Taabo Online si aad u aragto dadka Bogga Hore jooga.', 'Taabo Challenge ciyaaryahanka aad rabto.', 'Wuxuu haystaa waqti kooban oo uu ku aqbalo ama ku diido.', 'Samee qol oo koodhkiisa u dir asxaabta.', 'Si aad ugu biirto, geli koodhka qolka kadib taabo fallaaraha gelitaanka.']],
    [Gamepad2, '4. Sida loo ciyaaro', ['Marka wareeggaagu yimaado taabo laadhuuga.', 'Lix ayaa xoolo xerada ka soo saari kara.', 'Dooro xoolaha la dhaqaajin karo; server-ku ma aqbalo dhaqaaq khaldan.', 'Haddii hal xoolo keliya dhaqaaqi karo, si toos ah ayuu u dhaqaaqi karaa.', 'Qofkii xoolihiisa oo dhan hoyga geeya ayaa guuleysta; Kooxdu way wada shaqaysaa.']],
    [Eye, '5. Daawasho iyo saadaal', ['Ciyaaraha Tooska ah ka dooro Daawo.', 'Martidu ciyaarta way daawan kartaa iyada oo aan koonto gelin.', 'Laadhuuga, wareegga iyo dhaqaaqa xoolaha waqti-dhab ah ayaad u arkaysaa.', 'Saadaashu waxay u baahan tahay koonto iyo haraag ku filan.', 'Dooro ciyaaryahan ama koox, GUUL ama GUULDARRO, saami, kadib Gudbi.']],
    [Wallet, '6. Boorsada iyo lacagta', ['Header-ka ka taabo Boorsada.', 'Dhigaalka ka dooro adeeg-bixiye iyo qadar, kadib raac tilmaamaha.', 'La-bixidda geli qadarka iyo lambarka lacagta laguugu dirayo.', 'Codsigu wuxuu noqon karaa Sugaya, La oggolaaday ama La diiday.', 'Mar kasta hubi haraaga, khidmada iyo xaaladda macaamilka.']],
  ],
} as const;

const faq = {
  en: [['What can I do without signing in?', 'Explore Home, About Us, Help, leaderboards, stakes and live games, and watch an active match. Playing, Wallet, Challenge, chat and betting require an account.'], ['What do Online and Offline mean?', 'Online makes you visible to players waiting on Home. Offline hides your availability without signing you out.'], ['What if my internet disconnects?', 'Do not repeatedly tap dice or move. Wait for reconnection; the server keeps the verified state. Return Home and use Rejoin if needed.'], ['Why can a bet be refunded?', 'A bet may be refunded when a game is cancelled, no valid winner is confirmed or the market cannot produce a valid payout.'], ['How do I play the Bot?', 'Choose the stake and mode, then tap Play Against Bot. Check the wallet balance and Bot terms before starting.'], ['How do I join a tournament?', 'Open Tournaments, choose one with open registration, check its fee and schedule, register, then check in at the specified time.']],
  so: [['Maxaan samayn karaa anigoo aan koonto gelin?', 'Waxaad arki kartaa Bogga Hore, Nagu Saabsan, Caawin, kala-sarraynta, saamiyada iyo ciyaaraha socda; ciyaarna waad daawan kartaa. Ciyaarid, Boorso, Challenge, wada-hadal iyo saadaal waxay u baahan yihiin koonto.'], ['Online iyo Offline maxay yihiin?', 'Online wuxuu kaa dhigayaa mid ay arkaan dadka Bogga Hore jooga. Offline wuxuu qarinayaa joogitaankaaga adigoon koontada ka bixin.'], ['Maxaa dhacaya haddii internetku go’o?', 'Ha ku celcelin laadhuuga ama dhaqaaqa. Sug xiriirka; server-ku wuxuu hayaa xaaladda la xaqiijiyey. Haddii loo baahdo Bogga Hore ka isticmaal Dib ugu biir.'], ['Maxaa saadaal loo celin karaa?', 'Saadaal waa la celin karaa haddii ciyaarta la baajiyo, guuleyste sax ah la xaqiijin waayo ama suuqu samayn kari waayo lacag-bixin sax ah.'], ['Sideen Bot ula ciyaaraa?', 'Dooro saamiga iyo habka, kadib taabo La Ciyaar Bot. Hubi haraaga boorsada iyo shuruudaha ka hor bilaabidda.'], ['Sideen tartan uga qayb galaa?', 'Menu-ga ka fur Tartamada, dooro mid diiwaangelintiisu furan tahay, hubi khidmada iyo waqtiga, is-diiwaangeli, kadib xaadir waqtiga loo asteeyey.']],
} as const;

export default function Help({ onClose }: HelpProps) {
  useBodyScrollLock();
  const { language } = useLanguage();
  const so = language === 'so';
  const cards = so ? [['Marti','Hore + Daawo',Eye],['Ciyaaryahan','Ciyaar + Challenge',Gamepad2],['Boorsada','Dhigaal + La-bixid',Wallet],['Toos','Daawo + Saadaal',Radio]] : [['Guest','Home + Watch',Eye],['Player','Play + Challenge',Gamepad2],['Wallet','Deposit + Withdraw',Wallet],['Live','Spectate + Bet',Radio]];
  return <div className="fixed inset-0 z-[150] overflow-y-auto overscroll-contain touch-pan-y bg-[#040712] text-white [-webkit-overflow-scrolling:touch]">
    <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_85%_5%,rgba(37,99,235,.24),transparent_30%),radial-gradient(circle_at_8%_35%,rgba(124,58,237,.18),transparent_32%)]" />
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#070b18]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3 sm:px-7"><button onClick={onClose} className="flex items-center gap-2 rounded-xl border border-white/10 bg-white/5 px-3 py-2 text-xs font-black"><ArrowLeft className="h-4 w-4" /> {so ? 'Bogga Hore' : 'Home'}</button><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-500/15 text-blue-300"><HelpCircle className="h-5 w-5" /></span><div><div className="text-xs font-black">{so ? 'Xarunta Caawinta LudoSom' : 'LudoSom Help Center'}</div><div className="text-[8px] font-bold uppercase tracking-widest text-blue-300">{so ? 'Tilmaamaha isticmaalka' : 'User guide'}</div></div></div></div></header>
    <main className="relative mx-auto max-w-5xl px-4 pb-20 pt-8 sm:px-7 sm:pt-12">
      <section className="rounded-[28px] border border-blue-400/20 bg-gradient-to-br from-blue-950/70 via-slate-950/90 to-purple-950/70 p-6 sm:p-9"><span className="text-[9px] font-black uppercase tracking-[.28em] text-blue-300">{so ? 'Bilow halkan' : 'Start here'}</span><h1 className="mt-3 text-3xl font-black sm:text-5xl">{so ? 'Sidee LudoSom loo isticmaalaa?' : 'How do I use LudoSom?'}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-slate-300">{so ? 'Tilmaamahan wuxuu qof cusub ka bilaabayaa furitaanka app-ka ilaa koonto, boorso, ciyaar, daawasho iyo saadaal. Qayb kasta tallaabooyinkeeda sida ay u kala horreeyaan u raac.' : 'This guide takes a new user from opening the app through accounts, Wallet, playing, spectating and betting. Follow each section in order.'}</p></section>
      <section className="mt-5 grid gap-3 sm:grid-cols-4">{cards.map(([title,text,Icon]: any)=><div key={title} className="rounded-2xl border border-white/10 bg-white/[.045] p-4"><Icon className="h-5 w-5 text-blue-300" /><h2 className="mt-3 text-xs font-black">{title}</h2><p className="mt-1 text-[9px] font-bold text-slate-500">{text}</p></div>)}</section>
      <section className="mt-6 space-y-4">{guides[language].map(([Icon,title,steps]: any)=><article key={title} className="rounded-3xl border border-white/10 bg-slate-950/70 p-5 sm:p-6"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/15 text-blue-300"><Icon className="h-5 w-5" /></span><h2 className="text-base font-black sm:text-lg">{title}</h2></div><ol className="mt-5 grid gap-3 sm:grid-cols-2">{steps.map((step:string,index:number)=><li key={step} className="flex gap-3 rounded-xl border border-white/[.06] bg-white/[.035] p-3"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-blue-600 text-[10px] font-black">{index+1}</span><p className="text-[11px] font-medium leading-5 text-slate-300">{step}</p></li>)}</ol></article>)}</section>
      <section className="mt-6 grid gap-4 lg:grid-cols-2"><Info icon={Wifi} title={so ? 'Haddii ciyaartu gaabiso' : 'If the game becomes slow'} items={so ? ['Hubi xogta moobilka ama Wi‑Fi.','Hal mar taabo laadhuuga ama dhaqaaqa; sug server-ka.','Ha xirin app-ka inta gudbintu socoto.','Haddii qolku kaa lumo, Bogga Hore ka eeg Dib ugu biir.','APK-ga ku hay nooca ugu dambeeya.'] : ['Check mobile data or Wi‑Fi.','Tap dice or move once, then wait for the server.','Do not close the app while a submission is processing.','If the room disappears, look for Rejoin on Home.','Keep the APK on the latest version.']} /><Info icon={ShieldAlert} amber title={so ? 'Koontadaada ilaali' : 'Protect your account'} items={so ? ['Erayga sirta ah iyo OTP cidna ha siin.','Hubi telefoonka iyo iimaylka koontada.','Qadarka xaqiiji ka hor macaamil ama saadaal.','Qalab qalaad markaad isticmaasho ka bax koontada.','Ha isticmaalin lacag ka badan inta aad awooddo.'] : ['Never share your password or OTP.','Verify your account phone and email.','Confirm amounts before transactions or bets.','Sign out after using an unfamiliar device.','Never use more money than you can afford.']} /></section>
      <section className="mt-6 rounded-3xl border border-white/10 bg-white/[.035] p-6"><div className="flex items-center gap-3"><CircleDollarSign className="h-6 w-6 text-purple-300" /><h2 className="text-xl font-black">{so ? "Su'aalaha inta badan la weydiiyo" : 'Frequently asked questions'}</h2></div><div className="mt-5 divide-y divide-white/10">{faq[language].map(([q,a])=><details key={q} className="group py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-xs font-black"><span>{q}</span><span className="text-lg text-blue-300 transition group-open:rotate-45">+</span></summary><p className="mt-3 pr-7 text-[11px] leading-6 text-slate-400">{a}</p></details>)}</div></section>
      <section className="mt-6 rounded-3xl border border-purple-400/15 bg-purple-500/[.05] p-6 text-center"><Smartphone className="mx-auto h-7 w-7 text-purple-300" /><h2 className="mt-3 text-base font-black">{so ? 'Weli ma fahmin qayb?' : 'Still need help?'}</h2><p className="mx-auto mt-2 max-w-xl text-[11px] leading-6 text-slate-400">{so ? 'Raac qaybta falka aad rabto. Akhri fariinta khaladka, hubi internet-ka, kadib mar kale isku day. Hayso koodhka qolka, xaaladda macaamilka ama fariinta khaladka marka taageero loo baahan yahay.' : 'Follow the section for the action you need. Read any error, check your connection and try again. Keep the room code, transaction status or error message available if support is needed.'}</p></section>
    </main>
  </div>;
}

function Info({ icon: Icon, title, items, amber = false }: { icon: any; title: string; items: readonly string[]; amber?: boolean }) {
  return <article className={`rounded-3xl border p-6 ${amber ? 'border-amber-300/15 bg-amber-300/[.055]' : 'border-emerald-400/15 bg-emerald-500/[.055]'}`}><div className="flex items-center gap-3"><Icon className={`h-6 w-6 ${amber ? 'text-amber-300' : 'text-emerald-300'}`} /><h2 className="text-lg font-black">{title}</h2></div><ul className="mt-4 space-y-3 text-[11px] leading-5 text-slate-300">{items.map(item => <li key={item}>• {item}</li>)}</ul></article>;
}
